# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RegisterUi_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 14px;\n"
"    padding: 10px;\n"
"    background-color: rgb(226, 226, 226);\n"
"}\n"
"#register_2 {\n"
"    background: rgb(252, 252, 250);\n"
"}\n"
"#registerbtn {\n"
"    border: none;\n"
"    padding: 15px;\n"
"    border-radius: 14px;\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0.556, y1:0.051, x2:0.835455, y2:0.846, stop:0 rgba(12, 32, 55, 255), stop:1 rgba(37, 128, 146, 255));\n"
"}\n"
"#loginbtn {\n"
"    border: none;\n"
"    text-decoration: underline;\n"
"    color: rgb(0, 46, 255);\n"
"}\n"
"\n"
"#rightframe {\n"
"    border-radius: 14px;\n"
"    background: url(:/image/reg-bg.jpeg);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-size: cover;\n"
"}\n"
"#rightframe QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background: rgb(207, 255, 242);\n"
"}\n"
"#guestbtn {\n"
"    border: none;\n"
"    text-decoration: underline;\n"
"}\n"
"#registeruser {\n"
"    color: qlineargradient(spread:pad, x1:0.556, y1:0.051, x2:0.835455, y2:0.846, stop:0 rgba(12, 32, 55, 255), stop:1 rgba(37, 128, 146, 255));\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.register_2 = QtWidgets.QFrame(self.centralwidget)
        self.register_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.register_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.register_2.setObjectName("register_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.register_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_5 = QtWidgets.QFrame(self.register_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_9 = QtWidgets.QWidget(self.frame_5)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.registeruser = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.registeruser.setFont(font)
        self.registeruser.setObjectName("registeruser")
        self.verticalLayout_13.addWidget(self.registeruser, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_12.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(self.label_6)
        self.fullnameinput = QtWidgets.QLineEdit(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fullnameinput.setFont(font)
        self.fullnameinput.setObjectName("fullnameinput")
        self.verticalLayout_15.addWidget(self.fullnameinput)
        self.label_11 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.usernameinput = QtWidgets.QLineEdit(self.widget_11)
        self.usernameinput.setObjectName("usernameinput")
        self.verticalLayout_15.addWidget(self.usernameinput)
        self.label_12 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.ageinput = QtWidgets.QLineEdit(self.widget_11)
        self.ageinput.setObjectName("ageinput")
        self.verticalLayout_15.addWidget(self.ageinput)
        self.label_13 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.courseinput = QtWidgets.QLineEdit(self.widget_11)
        self.courseinput.setObjectName("courseinput")
        self.verticalLayout_15.addWidget(self.courseinput)
        self.label_7 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_15.addWidget(self.label_7)
        self.sectioninput = QtWidgets.QLineEdit(self.widget_11)
        self.sectioninput.setObjectName("sectioninput")
        self.verticalLayout_15.addWidget(self.sectioninput)
        self.label_14 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.passwordinput = QtWidgets.QLineEdit(self.widget_11)
        self.passwordinput.setObjectName("passwordinput")
        self.verticalLayout_15.addWidget(self.passwordinput)
        self.verticalLayout_14.addWidget(self.widget_11)
        self.verticalLayout_12.addWidget(self.widget_10)
        self.widget_13 = QtWidgets.QWidget(self.frame_5)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.registerbtn = QtWidgets.QPushButton(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.registerbtn.setFont(font)
        self.registerbtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.registerbtn.setObjectName("registerbtn")
        self.verticalLayout_17.addWidget(self.registerbtn, 0, QtCore.Qt.AlignTop)
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8, 0, QtCore.Qt.AlignRight)
        self.loginbtn = QtWidgets.QPushButton(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.loginbtn.setFont(font)
        self.loginbtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.loginbtn.setObjectName("loginbtn")
        self.horizontalLayout_3.addWidget(self.loginbtn)
        self.verticalLayout_17.addWidget(self.widget_14)
        self.verticalLayout_12.addWidget(self.widget_13, 0, QtCore.Qt.AlignTop)
        self.guestbtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.guestbtn.setFont(font)
        self.guestbtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.guestbtn.setObjectName("guestbtn")
        self.verticalLayout_12.addWidget(self.guestbtn)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.register_2)
        self.rightframe = QtWidgets.QFrame(self.centralwidget)
        self.rightframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightframe.setObjectName("rightframe")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.rightframe)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_15 = QtWidgets.QWidget(self.rightframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_9 = QtWidgets.QLabel(self.widget_15)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_19.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_10 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_19.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.widget_16 = QtWidgets.QWidget(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.weteach_2 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.weteach_2.setFont(font)
        self.weteach_2.setObjectName("weteach_2")
        self.verticalLayout_20.addWidget(self.weteach_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.description_2 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.description_2.setFont(font)
        self.description_2.setAlignment(QtCore.Qt.AlignCenter)
        self.description_2.setWordWrap(True)
        self.description_2.setObjectName("description_2")
        self.verticalLayout_20.addWidget(self.description_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_19.addWidget(self.widget_16)
        self.verticalLayout_18.addWidget(self.widget_15)
        self.horizontalLayout.addWidget(self.rightframe)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registeruser.setText(_translate("MainWindow", "REGISTER USER"))
        self.label_6.setText(_translate("MainWindow", "Full Name:"))
        self.label_11.setText(_translate("MainWindow", "UserName:"))
        self.label_12.setText(_translate("MainWindow", "Age:"))
        self.label_13.setText(_translate("MainWindow", "Contact:"))
        self.label_7.setText(_translate("MainWindow", "Program: "))
        self.label_14.setText(_translate("MainWindow", "Password: "))
        self.registerbtn.setText(_translate("MainWindow", "REIGSTER"))
        self.label_8.setText(_translate("MainWindow", "Already have an account?"))
        self.loginbtn.setText(_translate("MainWindow", "Log In"))
        self.guestbtn.setText(_translate("MainWindow", "Log In as Guest"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/image/logresize.png\"/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "AISAT COLLEGE DASMARINAS"))
        self.weteach_2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">We Teach, <span style=\" color:#ffff00;\">You Excel!</span></p></body></html>"))
        self.description_2.setText(_translate("MainWindow", "AISAT College – Dasmariñas (Asian Institute of Science and Technology) is a private institution located along Emilio Aguinaldo Highway in Dasmariñas, Cavite. Established in 1995, it offers a range of programs from basic education to specialized college and technical-vocational training"))
import assets_rc
