# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(933, 513)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 14px;\n"
"    padding: 15px;\n"
"    background-color: rgb(226, 226, 226);\n"
"}\n"
"#login {\n"
"    background: rgb(252, 252, 250);\n"
"}\n"
"#Loginbutton {\n"
"    border: none;\n"
"    padding: 15px;\n"
"    border-radius: 14px;\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0.556, y1:0.051, x2:0.835455, y2:0.846, stop:0 rgba(12, 32, 55, 255), stop:1 rgba(37, 128, 146, 255));\n"
"}\n"
"#Registerbutton {\n"
"    border: none;\n"
"    text-decoration: underline;\n"
"    color: rgb(0, 46, 255);\n"
"}\n"
"\n"
"#registerframe {\n"
"    border-radius: 14px;\n"
"    background: url(:/image/reg-bg.jpeg) no-repeat;\n"
"    background-position: center;\n"
"}\n"
"\n"
"#registerframe QLabel {\n"
"    color: white;\n"
"}\n"
"#centralwidget {\n"
"    background: rgb(207, 255, 242);\n"
"}\n"
"#guestbutton {\n"
"    border: none;\n"
"    text-decoration: underline;\n"
"}\n"
"#userlogin {\n"
"    \n"
"    color: qlineargradient(spread:pad, x1:0.556, y1:0.051, x2:0.835455, y2:0.846, stop:0 rgba(12, 32, 55, 255), stop:1 rgba(37, 128, 146, 255));\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerframe = QtWidgets.QFrame(self.centralwidget)
        self.registerframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.registerframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.registerframe.setObjectName("registerframe")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.registerframe)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.registerframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.weteach = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.weteach.setFont(font)
        self.weteach.setObjectName("weteach")
        self.verticalLayout_10.addWidget(self.weteach, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.description = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.description.setFont(font)
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout_10.addWidget(self.description, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.widget_7)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.registerframe)
        self.login = QtWidgets.QFrame(self.centralwidget)
        self.login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login.setObjectName("login")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.frame_4)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userlogin = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.userlogin.setFont(font)
        self.userlogin.setObjectName("userlogin")
        self.verticalLayout_2.addWidget(self.userlogin, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.frame_4)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.username = QtWidgets.QLineEdit(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.verticalLayout_7.addWidget(self.username)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.password = QtWidgets.QLineEdit(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.verticalLayout_8.addWidget(self.password)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.frame_4)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Loginbutton = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Loginbutton.setFont(font)
        self.Loginbutton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Loginbutton.setObjectName("Loginbutton")
        self.verticalLayout_9.addWidget(self.Loginbutton, 0, QtCore.Qt.AlignTop)
        self.widget_8 = QtWidgets.QWidget(self.widget_4)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5, 0, QtCore.Qt.AlignRight)
        self.Registerbutton = QtWidgets.QPushButton(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.Registerbutton.setFont(font)
        self.Registerbutton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Registerbutton.setObjectName("Registerbutton")
        self.horizontalLayout_2.addWidget(self.Registerbutton)
        self.verticalLayout_9.addWidget(self.widget_8)
        self.verticalLayout_3.addWidget(self.widget_4, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.login)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label_3.setText(_translate("LoginWindow", "<html><head/><body><p><img src=\":/image/logresize.png\"/></p></body></html>"))
        self.label.setText(_translate("LoginWindow", "AISAT COLLEGE DASMARINAS"))
        self.weteach.setText(_translate("LoginWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">We Teach, <span style=\" color:#ffff00;\">You Excel!</span></p></body></html>"))
        self.description.setText(_translate("LoginWindow", "AISAT College – Dasmariñas (Asian Institute of Science and Technology) is a private institution located along Emilio Aguinaldo Highway in Dasmariñas, Cavite. Established in 1995, it offers a range of programs from basic education to specialized college and technical-vocational training"))
        self.userlogin.setText(_translate("LoginWindow", "STAFF LOGIN"))
        self.label_2.setText(_translate("LoginWindow", "Username: "))
        self.label_4.setText(_translate("LoginWindow", "Password: "))
        self.Loginbutton.setText(_translate("LoginWindow", "LOG IN"))
        self.label_5.setText(_translate("LoginWindow", "Don\'t have an account?"))
        self.Registerbutton.setText(_translate("LoginWindow", "Ask admin to create account"))
import assets_rc
